# 阶段 1: build（用 Maven+JDK 编译）
FROM maven:3.9-eclipse-temurin-17-alpine AS build
WORKDIR /app

COPY backend/settings.xml /root/.m2/settings.xml

COPY pom.xml .
COPY backend/pom.xml backend/
RUN mvn -B dependency:go-offline -pl backend

COPY backend/src backend/src
RUN mvn -B package -DskipTests -pl backend

# 阶段 2: run（只用 JRE 运行）
FROM eclipse-temurin:17.0.19_10-jre-alpine
WORKDIR /app
COPY --from=build /app/backend/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
